[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"

[functions."aquire-topstats"]
schedule = "@hourly"

# [[redirects]]
# from = "/*"
# to = "/index.html"
# status = 200
